name: mlflow_test
channels:
  - defaults
dependencies:
  - numpy=1.19.2
  - pandas=1.1.3
  - pip=20.2.4
  - python=3.8.5
  - scikit-learn=0.23.2
  - scipy=1.5.2 
  - pip:
    - mlflow>=1.12.1
    - tensorflow == 2.3.1
    - keras==2.2.4